version: "3"
services:
    webapi:
        build: 
            context: .
            dockerfile: Dockerfile        
        ports:
            - "8000:80"
        depends_on:
            - db       
    db:
        image: "microsoft/mssql-server-linux:latest"
        environment:
            SA_PASSWORD: "P@ssw0rd"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
        ports:
            - "1433:1433"